sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t uanandu/docker-react_test -f Dockerfile.dev .

script:
    - docker run -e CI=true uanandu/docker-react_test npm run test -- --coverage
