sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t uanandu/docker-react_test -f Dockerfile.dev .

script:
    - docker run -e CI=true uanandu/docker-react_test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-123456789"
  bucket_path: "docker-react"
  on:
    branch: master