# from node
FROM node

# set working directory
WORKDIR /app

# copy package.json
COPY package.json .

# install dependencies
RUN npm install

# copy everything else
COPY . .

# default command
CMD ["npm", "run", "start"]